package simulation;

import javax.swing.JProgressBar;

/**
 *
 * @author eeu436
 */
public class CheckOutFrame extends javax.swing.JFrame {

    CheckOutSimulator sim;
    private final int MAX_ITEMS = 10;
    /**
     * Creates new form CheckOutFrame
     * Instantiates Simulation Object.
     */
    public CheckOutFrame() {
        setTitle("Check-out Simulator");
        sim = new CheckOutSimulator();
        sim.addCheckOutLines();
        initComponents();
        jProgressBar1.setMaximum(MAX_ITEMS);
        jProgressBar2.setMaximum(MAX_ITEMS);
        jProgressBar3.setMaximum(MAX_ITEMS);
        jProgressBar4.setMaximum(MAX_ITEMS);
        jProgressBar5.setMaximum(MAX_ITEMS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkOutItems6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        addShopperBtn = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        processBtn = new javax.swing.JButton();
        shopperField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        globalItemsLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkOutItems2 = new javax.swing.JLabel();
        checkOutItems3 = new javax.swing.JLabel();
        checkOutItems4 = new javax.swing.JLabel();
        checkOutItems1 = new javax.swing.JLabel();
        checkOutItems0 = new javax.swing.JLabel();
        globalCustomerCountLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkOutICustomer1 = new javax.swing.JLabel();
        checkOutCustomer2 = new javax.swing.JLabel();
        checkOutCustomer3 = new javax.swing.JLabel();
        checkOutCustomer0 = new javax.swing.JLabel();
        checkOutCustomer4 = new javax.swing.JLabel();

        checkOutItems6.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add to queues:");

        jLabel2.setText("No. of customers");

        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addShopperBtn.setText("Add");
        addShopperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShopperBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Customers left:");

        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        shopperField.setText("0");
        shopperField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopperFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Global items:");

        jLabel5.setText("Items left  p. checkout:");

        checkOutItems2.setText("0");

        checkOutItems3.setText("0");

        checkOutItems4.setText("0");

        checkOutItems1.setText("0");

        checkOutItems0.setText("0");

        globalCustomerCountLabel.setText("0");

        jLabel7.setText("Customers left p. checkout:");

        checkOutICustomer1.setText("0");

        checkOutCustomer2.setText("0");

        checkOutCustomer3.setText("0");

        checkOutCustomer0.setText("0");

        checkOutCustomer4.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(checkOutItems0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkOutItems1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkOutItems2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkOutItems3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkOutItems4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkOutCustomer0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkOutICustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkOutCustomer2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkOutCustomer3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkOutCustomer4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(processBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addShopperBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shopperField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(globalItemsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(globalCustomerCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(shopperField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(globalCustomerCountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addShopperBtn)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(globalItemsLabel))
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutItems0)
                    .addComponent(checkOutItems1)
                    .addComponent(checkOutItems2)
                    .addComponent(checkOutItems3)
                    .addComponent(checkOutItems4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutICustomer1)
                    .addComponent(checkOutCustomer2)
                    .addComponent(checkOutCustomer3)
                    .addComponent(checkOutCustomer0)
                    .addComponent(checkOutCustomer4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(processBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler, takes desired number of shoppers from user and triggers
     * algorithm that adds each shopper to currently shortest queue.
     * @param evt 
     */
    private void addShopperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShopperBtnActionPerformed
        
        int num = Integer.parseInt(shopperField.getText());
        sim.addCustomers(num);
        setValuesInInterface();
    }//GEN-LAST:event_addShopperBtnActionPerformed

    /**
     * Event handler for Process Button.
     * @param evt 
     */
    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        
        sim.processCustomerPerArr();       
        setValuesInInterface();
    }//GEN-LAST:event_processBtnActionPerformed
    
    /**
     * Changes values displayed in GUI.
     */
    private void setValuesInInterface(){
        
        jProgressBar1.setOrientation(JProgressBar.VERTICAL);
        jProgressBar2.setOrientation(JProgressBar.VERTICAL);
        jProgressBar3.setOrientation(JProgressBar.VERTICAL);
        jProgressBar4.setOrientation(JProgressBar.VERTICAL);
        jProgressBar5.setOrientation(JProgressBar.VERTICAL);
                
        globalItemsLabel.setText(Integer.toString(sim.getGlobalCustomerItemCount()));
        globalCustomerCountLabel.setText(Integer.toString(sim.getGlobalCustomerCount()));
        
        jProgressBar1.setValue(sim.getCurrentQueueFrontItems(0));
        jProgressBar2.setValue(sim.getCurrentQueueFrontItems(1));
        jProgressBar3.setValue(sim.getCurrentQueueFrontItems(2));
        jProgressBar4.setValue(sim.getCurrentQueueFrontItems(3));
        jProgressBar5.setValue(sim.getCurrentQueueFrontItems(4));
        
        checkOutItems0.setText(Integer.toString(sim.getCurrentGlobalItemsPerQueue(0)));
        checkOutItems1.setText(Integer.toString(sim.getCurrentGlobalItemsPerQueue(1)));
        checkOutItems2.setText(Integer.toString(sim.getCurrentGlobalItemsPerQueue(2)));
        checkOutItems3.setText(Integer.toString(sim.getCurrentGlobalItemsPerQueue(3)));
        checkOutItems4.setText(Integer.toString(sim.getCurrentGlobalItemsPerQueue(4)));
        
        checkOutCustomer0.setText(Integer.toString(sim.getCustomerCountPerQueue(0)));
        checkOutICustomer1.setText(Integer.toString(sim.getCustomerCountPerQueue(1)));
        checkOutCustomer2.setText(Integer.toString(sim.getCustomerCountPerQueue(2)));
        checkOutCustomer3.setText(Integer.toString(sim.getCustomerCountPerQueue(3)));
        checkOutCustomer4.setText(Integer.toString(sim.getCustomerCountPerQueue(4)));
    }
    
    private void shopperFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopperFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shopperFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addShopperBtn;
    private javax.swing.JLabel checkOutCustomer0;
    private javax.swing.JLabel checkOutCustomer2;
    private javax.swing.JLabel checkOutCustomer3;
    private javax.swing.JLabel checkOutCustomer4;
    private javax.swing.JLabel checkOutICustomer1;
    private javax.swing.JLabel checkOutItems0;
    private javax.swing.JLabel checkOutItems1;
    private javax.swing.JLabel checkOutItems2;
    private javax.swing.JLabel checkOutItems3;
    private javax.swing.JLabel checkOutItems4;
    private javax.swing.JLabel checkOutItems6;
    private javax.swing.JLabel globalCustomerCountLabel;
    private javax.swing.JLabel globalItemsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JButton processBtn;
    private javax.swing.JTextField shopperField;
    // End of variables declaration//GEN-END:variables
}
